### ISSUE TITLE
Can I do it without Edge TPU ?

### ISSUE THREAD

**Issue by MujoNoThuki** [maxbbraun/thermal-face#11] opened 2020-11-24 09:04 UTC
I'm new to python, so I'm sorry if it's a stupid question.
I don't have device "EdgeTPU" ...
But I have another thermal camera and a thermal image taken with that camera.
Is face detection possible even in such cases?

**Comment by maxbbraun** [comment] 2020-11-24 17:00
Duplicate of #9

**Closed by maxbbraun** 2020-11-24 17:00 UTC

**Comment by MujoNoThuki** [comment] 2020-11-25 07:37
Thank you for your reply while you are busy. Specifically, when using "thermal_face_automl_edge_fast.tflite", how should I write the
 "face_detector = DetectionEngine ('thermal_face_automl_edge_fast_edgetpu.tflite')" part?

**Comment by maxbbraun** [comment] 2020-11-25 16:38
You could run TF Lite inference from scratch. Check out [this guide](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python) and use [this info](https://github.com/maxbbraun/thermal-face/releases/tag/v1.0) about the input and output tensor sizes. You can also look at the [source code](https://github.com/google-coral/edgetpu/blob/master/edgetpu/detection/engine.py) of DetectionEngine to see how they did it.
